os: linux

language:
  - java
  - node_js

jdk: openjdk17

node_js:
  - "18"

dist: jammy #ubuntu 22.04

services: postgresql # postgres 14.5+

before_install:
  # Create test database
  - psql -c 'create database travis_ci_test;' -U postgres
  # use travis configuration
  - cd WebBackend
  - cp -f /src/main/resources/application.properties.travis src/main/resources/application.properties
  - chmod +x mvnw
  - ./mvnw compile
  - ./mvnw spring-boot:run &
  # use localhost api endpoint
  - cd ../webfrontend
  - echo "export const API_URL = \"http://localhost:8080\";" > src/js/config.js
  - npm install
  - npm run start &
  - sleep 10s
  - cd ../functional-tests

script:
  - mvn test
